SpringBoot:
  image: michaelzx/spring-boot-jre8
  volumes:
  - /Users/michael/workspace/project2017/dlg/code/build/libs:/www
  - /etc/localtime:/etc/localtime:ro
  ports:
  - 8081:8080
  environment:
  - JAVA_OPTS=-Duser.timezone=GMT+08 -Xms10m -Xmx100m
  - APP_NAME=app-0.0.1-SNAPSHOT.jar
  - PROFILES_ACTIVE=prod
  restart: always